### ISSUE TITLE
Reposition the hamburger icon

### ISSUE THREAD

**Issue by ankiiitraj** [houseofgeeks/hg#65]
### Description
<write your description>
The current position of the hamburger icon is confusing.
Share what position it should be put so that it makes some sense of what purpose it is meant for!

### Screenshots/testimonials
<place your screenshots or testimonials here if applicable>
N/A

**Comment by ankiiitraj** [comment]
@EmperorYP7 @tusharjain0022  @EricLiclair suggestions?

**Comment by tusharjain0022** [comment]
we can place it in the top right corner where hamburger icon is placed usually so that the user can easily get idea what purpose does it serve or we can also add a tooltip to the icon to make it more clear.

### Screenshot

![Screenshot (416)](https://user-images.githubusercontent.com/59157988/93891033-96376580-fd08-11ea-988b-7c4751dbc9c2.png)

**Comment by EmperorYP7** [comment]
@tusharjain0022 you might do some wavy shape for the hamburger icon just like in the wireframe..
https://www.figma.com/proto/NyIGhH5PhxbjfDf4DNmW55/House-of-Geeks?node-id=107%3A74&scaling=min-zoom

![image](https://user-images.githubusercontent.com/62606998/93913899-5a5dc980-fd23-11ea-85ea-6b2a73ddd6c6.png)

Also, the hamburger should be resized in mobile view as it is relatively large. The desktop version however, is perfect!

**Comment by ankiiitraj** [comment]
@tusharjain0022 Maintain the ratio of the lengths of 3 three lines in the hamburger icon!

**Comment by tusharjain0022** [comment]
working on it 🙌

**Comment by ankiiitraj** [comment]
closing against #74
